### ISSUE TITLE
where you find the lattitude_longitude.txt file, thanks.

### ISSUE THREAD

**Issue by liamxg** [ozancanozdemir/CoronaDataVisualization#1]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/46078579/204721684-0ced7358-bfa4-48dc-98fa-feb601e5cee4.png">

**Comment by liamxg** [comment]
@ozancanozdemir where you find the lattitude_longitude.txt file?

**Comment by ozancanozdemir** [comment]
@liamxg I got them from Google Data Souce (https://developers.google.com/public-data/docs/canonical/countries_csv)

**Comment by liamxg** [comment]
@ozancanozdemir  thanks. :)
