### ISSUE TITLE
not match of the us?

### ISSUE THREAD

**Issue by liamxg** [ozancanozdemir/CoronaDataVisualization#2]
Taiwan    51      TW  23.697810  120.960515               Taiwan
27             Thailand    94      TH  15.870032  100.992541             Thailand
28                   UK     2      TH  51.477780   -0.001390       United Kingdom
29                   US    39      AE  23.424076   53.847818 United Arab Emirates
30 United Arab Emirates    12      US  37.090240  -95.712891        United States
31              Vietnam    18      VN  14.058324  108.277199              Vietnam

**Comment by ozancanozdemir** [comment]
What is your data source?
